### ISSUE TITLE
Very nice masterpiece!

### ISSUE THREAD

**Issue by ScottishFold007** [TheDenk/images_mixing#1]
Very nice masterpiece! Can you realize“Doing CLIP guidance for text to image generation with Stable Diffusion” using stable-diffusion-xl-base-1.0?
here：https://github.com/huggingface/diffusers/tree/main/examples/community#clip-guided-stable-diffusion

**Comment by TheDenk** [comment]
Thank you :) Probably later because now I have no time for this.
