### ISSUE TITLE
Theorical explanation

### ISSUE THREAD

**Issue by wadie999** [TheDenk/images_mixing#3]
Hello, very interesting project. Is there any paper or deeper explanation of mixing process ? 
Is there a way of mixing 2 images but preserving informations from an image when mixing ? 
for example mixing a QR code with an image but preserving the QR Code modules.

**Comment by TheDenk** [comment]
Hey.
1. There is no paper or deeper explanation. I just came up with this when I saw the code from [clip_guided_stable_diffusion_img2img](https://github.com/huggingface/diffusers/blob/main/examples/community/clip_guided_stable_diffusion_img2img.py) pipeline.
2. For images mixing with preserving information (QR Code or other) it is better to use approaches with controlnet or ip-adapter.

**Comment by wadie999** [comment]
Hey Denk, thank you for the insights
I was wondering, is it possible to mix images without prompts ? I see that even if you take 2 images as inputs, the coca model create captions that serves as prompt to guide the generation. Do you think the diffusion process can rely on image embeddings in latent space ? using a vision encoder

**Comment by TheDenk** [comment]
Hi @wadie999 :)
If I understand you correctly there is a [ jupyter-notebook example](https://github.com/TheDenk/images_mixing/blob/main/jupyters/example-no-CoCa.ipynb) which does not use coca model. So you can pass empty string.
Also if you interested in mix images you try to use [Kandinsky](https://github.com/ai-forever/Kandinsky-2?tab=readme-ov-file#2-image-fuse) model for this purpose.
